version: '3.4'

services:
  speech-api:
    image: speech-api
    build:
      context: .
      dockerfile: services/SpeechApi/Dockerfile
    environment:
      - PULSE_SERVER=unix:/run/user/1000/pulse/native
      - ASPNETCORE_URLS=http://+:8080
    ports:
      - "8082:8080"

    volumes:
      - /run/dbus/system_bus_socket:/run/dbus/system_bus_socket
      - /run/user/1000/pulse/native:/run/user/1000/pulse/native
    user: 1000:1000
  camera-api:
    image: camera-api
    build:
      context: .
      dockerfile: services/CameraApi/Dockerfile
    environment:
      - ASPNETCORE_URLS=http://+:8080
    ports:
      - "8083:8080"

    volumes:
      - /dev/video0:/dev/video0
    user: 1000:1000
    privileged: true
  system-api:
    depends_on:
      - speech-api
      - camera-api
    image: system-api
    build:
      context: .
      dockerfile: services/SystemApi/Dockerfile
    environment:
      - ASPNETCORE_URLS=http://+:8080
    ports:
      - "8081:8080"

    volumes:
      - /bin/systemctl:/bin/systemctl
      - /run/systemd/system:/run/systemd/system
      - /sys/fs/cgroup:/sys/fs/cgroup
      - /run/dbus/system_bus_socket:/run/dbus/system_bus_socket
    user: 1000:1000
    privileged: true
