
version: '3.4'

services:
  helloespeak:
    image: helloespeak
    build:
      context: .
      dockerfile: HelloESpeak.Dockerfile
    environment:
      - PULSE_SERVER=unix:/run/user/1000/pulse/native
    volumes:
      - /run/dbus/system_bus_socket:/run/dbus/system_bus_socket
      - /run/user/1000/pulse/native:/run/user/1000/pulse/native
    user: 1000:1000
