version: '3.4'

services:
  rabbitmq:
    image: masstransit/rabbitmq:latest
    ports:
     - "5672:5672"
     - "15672:15672"
     - "15692:15692"

  speech-service:
    depends_on:
      - rabbitmq
    image: speech-service
    build:
      context: .
      dockerfile: services/SpeechService/Dockerfile
    environment:
      - PULSE_SERVER=unix:/run/user/1000/pulse/native
      - ASPNETCORE_URLS=http://+:8080
    ports:
      - "8080:8080"

    volumes:
      - /run/dbus/system_bus_socket:/run/dbus/system_bus_socket
      - /run/user/1000/pulse/native:/run/user/1000/pulse/native
    user: 1000:1000
  system-state:
    depends_on:
      - rabbitmq
      - speech-service
    image: system-state
    build:
      context: .
      dockerfile: services/SystemState/Dockerfile

    volumes:
      - /run/dbus/system_bus_socket:/run/dbus/system_bus_socket
      - /run/user/1000/pulse/native:/run/user/1000/pulse/native
    user: 1000:1000

  camera-api:
    image: camera-api
    build:
      context: .
      dockerfile: services/CameraApi/Dockerfile
    environment:
      - ASPNETCORE_URLS=http://+:8080
    ports:
      - "8081:8080"

    volumes:
      - /dev/video0:/dev/video0
    user: 1000:1000
    privileged: true
